# Предупреждение: при изменении admin_tg_id 
# прошлый главный администратор остается администратором(но не главным) 

[bot]

# bot_token выдает BotFather при создании бота
# admin_tg_id - id главного админа

bot_token = 
admin_tg_id = 

[database]
database_url = sqlite:///./data/achievements.db

[logs]
logs_path = ./data/logs.txt
